- name: "Sync configs project {{ project }} / {{ repo_name }} to {{ configs_branch }}"
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
    - "{{ playbook_dir }}/vars/localenv.yml"

  tasks:
    - name: "Load vars from vault file"
      include_vars: "{{ config_dir + '/' + configs_branch + '/vault.yml' }}"
      when: (config_dir + '/' + configs_branch + '/vault.yml') is file

    - name: "Copy templated configs from : {{ config_dir + '/' + configs_branch }} to {{ source_dir }}"
      template:
        src: "{{  config_dir + '/' + configs_branch + '/' + item }}"
        dest: "{{ source_dir + '/' + item|regex_replace('\\.j2','') }}"
      loop: "{{ lookup('filetree',config_dir + '/' + configs_branch + '/', wantlist=True )|reject('search','.parent|vault.yml')|selectattr('state','equalto','file')|map(attribute='path')|select('search','.j2')|list }}"
