- name: "Sync configs project {{ project }} / {{ repo_name }} to {{ configs_branch }}"
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
    - "{{ playbook_dir }}/vars/localenv.yml"
    - "{{ playbook_dir }}/vars/configs.yml"
  tasks:
    - name: "Create all configs dirs"
      file:
        dest: "{{ source_dir + '/' + item }}"
        state: directory
      loop: "{{ configs_dirs }}"

    - name: "Symlink configs from {{ config_dir + '/' + configs_branch }} to {{ source_dir }}"
      file:
        src: "{{  config_dir + '/' + configs_branch + '/' + item }}"
        dest: "{{ source_dir + '/' + item }}"
        state: link
        force: yes
      loop: "{{ configs_files }}"

    - name: "Load vars from vault file"
      include_vars: "{{ config_dir + '/' + configs_branch + '/vault.yml' }}"
      when: (config_dir + '/' + configs_branch + '/vault.yml') is file

    - name: "Copy templated configs from : {{ config_dir + '/' + configs_branch }} to {{ source_dir }}"
      template:
        src: "{{  config_dir + '/' + configs_branch + '/' + item }}"
        dest: "{{ source_dir + '/' + item }}"
      loop: "{{ configs_templates }}"
