- name: "Create all configs dirs"
  file:
    dest: "{{ source_dir + '/' + configs_dirs.path }}"
    state: directory
  when: configs_dirs.state == 'directory'
  loop: "{{ [ lookup('filetree',config_dir + '/' + configs_branch + '/') ] }}"
  loop_control:
    loop_var: configs_dirs

- name: "Symlink configs from : {{ config_dir + '/' + config_branch }} to {{ source_dir }}"
  file:
    src: "{{  symlink_file.src }}"
    dest: "{{ source_dir + '/' + symlink_file.path }}"
    state: link
    force: yes
  when: symlink_file.state == 'file' and symlink_file.src.find('.j2') == -1 and symlink_file.src|basename not in ['.parent' , '.gitignore' , 'vault.yml' , '.gitlab-ci.yml']
  loop: "{{ [ lookup('filetree',config_dir + '/' + configs_branch + '/') ] }}"
  loop_control:
    loop_var: symlink_file

- name: "Load vars from vault file"
  include_vars: "{{ config_dir + '/' + configs_branch + '/vault.yml' }}"
  when: (config_dir + '/' + configs_branch + '/vault.yml') is file

- name: "Copy templated configs from : {{ config_dir + '/' + config_branch }} to {{ source_dir }}"
  template:
    src: "{{  templated_file.src }}"
    dest: "{{ source_dir + '/' + templated_file.path }}"
  when: templated_file.state == 'file' and templated_file.src.find('.j2') != -1 and templated_file.src|basename not in ['.parent' , '.gitignore' , 'vault.yml' , '.gitlab-ci.yml']
  loop: "{{ [ lookup('filetree',config_dir + '/' + configs_branch + '/') ] }}"
  loop_control:
    loop_var: templated_file
