- name: "Templating project {{ project }} / {{ repo_name }} service files"
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
    - "{{ playbook_dir }}/vars/localenv.yml"
    - "{{ playbook_dir }}/projects/{{ project }}.yml"
  tasks:
    - name: "Extract variables for {{ project }} / {{ repo_name }}"
      set_fact:
        "{{ item.key }}": "{{ item.value }}"
      loop: "{{ lookup('vars',repo_name)|dict2items }}"

    - name: "Load tech oriented variables"
      include_vars:
        dir: "{{ playbook_dir + '/vars/tech' }}"
        files_matching: "{{ tech + '.yml' }}"

    - name: "Load docker-compose services primitives"
      set_fact:
        services_primitives: "{{ services_primitives|default({})|combine(lookup('template', services_primitives + item + '.yml.j2')|from_yaml) }}"
      loop: "{{ services.keys() }}"

    - name: "Merge docker-compose project services with services primitives"
      set_fact:
        services: "{{ services_primitives|combine(services|dict2items|rejectattr('value','equalto',none)|list|items2dict,recursive=True) }}"

    - name: "Generate persistent_volumes list"
      set_fact:
        persistent_volumes: "{{ persistent_volumes|default([]) + item.value['volumes']|flatten|reject('search',':')|map('regex_replace','(.*)',item.key + '\\1')|list  }}"
      when: item.value['volumes'] is defined
      loop: "{{ services|dict2items }}"

    - name: "Create docker-compose services dirs for project : {{ project }}/{{ repo_name }}"
      file:
        path: "{{ service_dir }}/{{ item }}"
        state: directory
      when: item in services.keys()
      loop: "{{ templates_dirs }}"

    - name: "Render templateds for project : {{ project }}/{{ repo_name }}"
      template:
        src: "{{ playbook_dir }}/templates/{{ item }}"
        dest: "{{ service_dir }}/{{ item|regex_replace('\\.j2','') }}"
        mode: preserve
      when: item in ['Makefile.j2','docker-compose.yml.j2'] or item|dirname in services.keys()
      loop: "{{ templates_templates }}"

    - name: "Render files for project : {{ project }}/{{ repo_name }}"
      copy:
        src: "{{ playbook_dir }}/templates/{{ item }}"
        dest: "{{ service_dir }}/{{ item }}"
        mode: preserve
      when: item|dirname in services.keys()
      loop: "{{ templates_files }}"
