- name: "Deploy poject {{ project }} / {{ repo_name }}"
  hosts: localhost
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
    - "{{ playbook_dir }}/vars/localenv.yml"
    - "{{ playbook_dir }}/projects/{{ project }}.yml"
  tasks:
    - name: "Extract variables for {{ project }} / {{ repo_name }}"
      set_fact:
        "{{ item.key }}": "{{ item.value }}"
      loop: "{{ lookup('vars',repo_name)|dict2items }}"

    - name: "Load tech oriented variables/services_default dictionary"
      include_vars:
        dir: "{{ playbook_dir + '/vars/' }}"
        files_matching: "{{  tech + '.yml' }}|services_default.yml"

    - name: "Create package cache directory for tech {{ tech }} - {{ cache_dirs[tech]|regex_replace('^.*:(.*)$','\\1') }}"
      file:
        path: "{{ cache_dirs[tech]|regex_replace('^.*:(.*)$','\\1') }}"
        state: directory
      when: tech in cache_dirs.keys()

    - name: "Create projects/services directories"
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ service_dir }}"
        - "{{ source_dir }}"

    - name: "Generate services_merged from services_default"
      set_fact:
        services_merged: "{{ services_merged|default({})|combine({item: services_default[item]}) }}"
      when: services_default[item] is defined
      loop: "{{ services.keys() }}"

    - name: "Merge services_merged from services"
      set_fact:
        services_merged: "{{ services_merged|combine({item: services[item]},recursive=True) }}"
      when: services[item] is mapping
      loop: "{{ services.keys() }}"

    - name: "Generate cli_depends_on list"
      set_fact:
        cli_depends_on: "{{ cli_depends_on|default([]) + [ item.key ] }}"
      when: item.key not in ['cli','nginx'] and 'cli' in services_merged.keys() and item.value['image'] != services_merged['cli']['image'] + '_' + project + '_' + repo_name
      loop: "{{ services_merged|dict2items }}"

    - name: "Generate persistent_volumes list"
      set_fact:
        persistent_volumes: "{{ persistent_volumes|default([]) + item.value['volumes']|flatten|reject('search',':')|map('regex_replace','(.*)',item.key + '\\1')|list  }}"
      when: item.value['volumes'] is defined
      loop: "{{ services_merged|dict2items }}"

    - name: "Create dcoker-composer services dirs for project : {{ project }}/{{ repo_name }}"
      file:
        path: "{{ service_dir }}/{{ item.path }}"
        state: directory
      when: item.state == 'directory' and item.path in services_merged.keys()
      loop: "{{ lookup('filetree',playbook_dir + '/templates/') }}"

    - name: "Render templated services files for project : {{ project }}/{{ repo_name }}"
      template:
        src: "{{ playbook_dir }}/templates/{{ item.path }}"
        dest: "{{ service_dir }}/{{ item.path|regex_replace('\\.j2','') }}"
        mode: preserve
      when: item.state == 'file' and item.path is search ('.j2') and ( item.path in ['Makefile.j2' , 'docker-compose.yml.j2'] or item.path|dirname in services_merged.keys() )
      loop: "{{ lookup('filetree',playbook_dir + '/templates/') }}"

    - name: "Render services files for project : {{ project }}/{{ repo_name }}"
      copy:
        src: "{{ playbook_dir }}/templates/{{ item.path }}"
        dest: "{{ service_dir }}/{{ item.path }}"
        mode: preserve
      when: item.state == 'file' and item.path is not search ('.j2') and item.path|dirname in services_merged.keys()
      loop: "{{ lookup('filetree',playbook_dir + '/templates/') }}"

    - name: "Code receive block"
      block:
        - name: "Git pull branch: {{ branch|default(git_code_branch_default) }} from {{ git_server }}{{ project }}/{{ repo_name }}.git to {{ source_dir }}"
          git:
            accept_hostkey: yes
            dest: "{{ source_dir }}"
            repo: "{{ git_server }}{{ project }}/{{ repo_name }}.git"
            version: "{{ branch|default('master') }}"
            force: "{{ get_code_force|default('no') }}"
      rescue:
        - name: fail on error
          fail:
            msg: "Filed: Git pull branch: {{ branch|default('master') }} from {{ git_server }}{{ project }}/{{ repo_name }}.git to {{ source_dir }} \
                  - lock Pull is not possible because you have unmerged files. Please, fix them up in the work tree"
      when: tech not in ['service']
