{{ project }}-{{ repo_name }}-images-pull:
	@docker-compose -f {{ service_dir }}/docker-compose.yml pull
{{ project }}-{{ repo_name }}-up:
	@docker-compose -f {{ service_dir }}/docker-compose.yml up -d
{{ project }}-{{ repo_name }}-down:
	@docker-compose -f {{ service_dir }}/docker-compose.yml down
{{ project }}-{{ repo_name }}-restart:  {{ project }}-{{ repo_name }}-down  {{ project }}-{{ repo_name }}-up
{% if 'cli' in services %}
{{ project }}-{{ repo_name }}-build:
	@docker-compose -f {{ service_dir }}/docker-compose.yml down
	@docker-compose -f {{ service_dir }}/docker-compose.yml build
	@docker-compose -f {{ service_dir }}/docker-compose.yml up -d {{ project }}-{{ repo_name }}-cli
	@docker exec {{ project }}-{{ repo_name }}-cli /build.sh
	@docker-compose -f {{ service_dir }}/docker-compose.yml up -d
{{ project }}-{{ repo_name }}-exec:
	@docker exec -ti {{ project }}-{{ repo_name }}-cli bash -l
{% endif %}
{% if repo_name == 'localenv' %}
dns:
	@docker restart dev-localenv-dind
{% endif %}
{% if project == 'dev' %}
sre:
	@sudo service docker restart
{% endif %}
{% if 'redis' in services %}
{{ project }}-{{ repo_name }}-exec-redis-cli:
	@docker exec -ti {{ project }}-{{ repo_name }}-redis redis-cli
{{ project }}-{{ repo_name }}-publish-redis:
	@docker ps -q --filter "name=dev-publish-redis" | grep -q . && docker stop dev-publish-redis || exit 0
	@docker run -d --rm --name dev-publish-redis --publish 6379:6379 --network=localenv alpine/socat tcp-listen:6379,fork,reuseaddr tcp-connect:{{ project }}-{{ repo_name }}-redis:6379
{% endif %}
{% if 'workers' in services %}
{{ project }}-{{ repo_name }}-exec-workers:
	@docker exec -ti {{ project }}-{{ repo_name }}-workers bash -l
{% endif %}
{% if 'fpm' in services %}
{{ project }}-{{ repo_name }}-exec-fpm:
	@docker exec -ti {{ project }}-{{ repo_name }}-fpm bash -l
{% endif %}
