FROM {{ services['postgres12']['image'] }}

ENV POSTGRES_HOST_AUTH_METHOD trust

COPY ./createExtensions.sh /docker-entrypoint-initdb.d/

RUN apt-get update
RUN apt-get install -y postgresql-12-postgis-3
RUN apt-get remove --purge -y software-properties-common python-software-properties
RUN apt-get autoremove -y
RUN apt-get clean
RUN apt-get autoclean
RUN rm -rf /var/lib/apt/lists/*
RUN chmod +x /docker-entrypoint-initdb.d/createExtensions.sh
