FROM {{ services['runner']['image'] }}

RUN apk -u add bash mc make git rsync docker-compose ansible shadow

ENV ANSIBLE_DISPLAY_SKIPPED_HOSTS=false
ENV PY_COLORS=1
ENV ANSIBLE_FORCE_COLOR=1

ENV LE_NET_GW={{ lookup('env','LE_NET_GW') }}
ENV USER={{ ansible_user }}
ENV OS_NAME={{ os_name }}

RUN if [ $(getent group {{ ansible_user_gid }}) ]; then groupmod -n {{ ansible_user }} -g {{ ansible_user_gid }} $(getent group {{ ansible_user_gid }}|cut -d ":" -f1); \
    else groupadd --gid {{ ansible_user_gid }} {{ ansible_user }}; fi
RUN if [ $(getent passwd {{ ansible_user_uid }}) ]; then usermod -d {{ home_dir }} -s /bin/bash -l {{ ansible_user }} -u  {{ ansible_user_uid }} -g {{ ansible_user_gid }} $(getent passwd {{ ansible_user_uid }}|cut -d ":" -f1); mkhomedir_helper {{ ansible_user }}; \
    else useradd -m --home {{ home_dir }} -s /bin/bash {{ ansible_user }} --uid  {{ ansible_user_uid }} --gid  {{ ansible_user_gid }}; fi
RUN if [ $(getent group {{ docker_gid }}) ]; then groupmod -n docker -g {{ docker_gid }} $(getent group {{ docker_gid }}|cut -d ":" -f1); \
    else groupadd --gid {{ docker_gid }} docker; fi
RUN usermod -aG docker {{ ansible_user }}
USER {{ ansible_user }}
WORKDIR {{ lookup('env','PWD') }}
CMD /bin/bash
